language: c

sudo: true

env:
  global:
    # Git and Github credentials for pushing documentation
    - GIT_NAME=poppy-bot
    - GIT_EMAIL=poppy-bot-ci@inria.fr
    # GH_TOKEN encrypted below > travis encrypt GH_TOKEN=XXXXXX --add
    # You have to overwrite your hown token to push the documentation to your repo.
    - secure: "fYucfEgR1PU9amVFMkrlSFL0b0WmMC+fUyobO9GbbYgsHngFhrWtvhkgtNCeGK5vR/mKclT7tnU/0Tf/wT+Qz11HDSwVMhQPua3t5lsN+RkrtPZ2Q8yScEDtZq48jrPHsiXEPn+GV/J5RP1YAKLCGEI+KJMQuIYwfM6CIb47EPk="

matrix:
  include:
    - os: linux
      language: c
      env: SUITE=tests

    - os: linux
      language: c
      env: SUITE=build

install:
  - . ./extra/ci/install.sh

script:
 - . ./extra/ci/script.sh

after_success:
 - . ./extra/ci/after_success.sh

notifications:
  email:
    - secure: "XNZOOSgfG1Z460l9HWAcAMZYyQbfD9LpMJTiZYjySPW5gGmgtKzxxRYnsJlgMDeP6NUOn6VG7u6CFbuxPSQo4rZODntN21xKI+4Ketah8jYGkTK0qwf7fA3K9KGdYbVQTMsudHm5GjOjt6CuKi++Tq4ZqhB3cJxUzGPNYtiRmR0="
  on_failure: change
  on_success: change
  slack:
    - secure: ff2ZS7GGHeLZrDXz51Fw3oLdNtZe3Y16Q+WdPFxz8hPU84Eg0BMZNwOQjrE651XQWWILKzYNuOEz6m9ktvBHnTB7+WXgnm3M3VXlWBN78GiGdAAXbUMR1JuaKEJSAHdRrSqtXjQOTjjFRSo+XEOuVKfnygNl9U7KVpvhrrj12FA=
  sla:
    - secure: T5uJOsXeh28QKW9oVw3gkC7bL7gVWixwgCRdWxRyaFKJUnaa4h9Spxfvo/jwvbGi7fRyVyWynShLnclASb8g3DZ5GLaOe7HjJaUE4wbV9Yo7P/xQcuWa31MOWNgKy+tfaThJlE3QbPhHNJg+1Ykx9NfqrK6gqE+b3D706erYfPs=
